# Generated by Django 4.2.5 on 2023-09-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item_name',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
    ]
